### ISSUE TITLE
Long Wait after "Submit" & Screen Message

### ISSUE THREAD

**Issue by kareenk** [clssc/reg#7]
Browser: Google Chrome

Link used: English

1. After entering family number, clicked on "Submit"
- long wait with "Transmitting Data" dialog box
- nothing happened so closed dialog box

2. Then clicked on "Payment"
- Screen says "You need to pay"  in addition to payment success message.

Thanks, Arthur for doing this!

**Comment by arthurhsu** [comment]
Fixed the progress dialog not closing part.
The "You need to pay" shall say "You need to pay $1200" or some other amount depending on family number and service points.

I think I have fixed it. Please test it after 1/12 since iPower caches the web page for a while.

**Comment by arthurhsu** [comment]
Fixed
